# ------------------------------------------------
# Override DEV uniquement
# ------------------------------------------------
services:

  php:
    volumes:
      - .:/var/www/symfony
      - php_cache:/var/www/symfony/var/cache
      - php_log:/var/www/symfony/var/log
      - symfony_vendor:/var/www/symfony/vendor
      - assets_vendor:/var/www/symfony/assets/vendor
    ports:
      - "8081:80" # 8080 est pris par Cabin Access

volumes:
  php_cache:
  php_log:
  symfony_vendor:
  assets_vendor:
