# ------------------------------------------------
# Override PREPROD
# ------------------------------------------------
services:

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.preprod
    container_name: portfolio_php_preprod
    ports:
      - "8081:80"
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
    env_file:
      - .env.local                   # ← APP_SECRET depuis le VPS
