<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Page /uses : une seule ligne, modifiée dans l'administration (comme /now). Premier contenu : à compléter (matériel).
 */
final class Version20261010090000 extends AbstractMigration
{
    private const CONTENU_FR = "## Logiciels\n\n- **PhpStorm** pour le code\n- **Docker** pour tout faire tourner en local comme en production\n- **Claude Code** comme binôme\n\n## Stack de ce site\n\n- **PHP 8.5** et **Symfony 8**, **Doctrine** sur **PostgreSQL**\n- **EasyAdmin** pour l'administration\n- **Stimulus** et **AssetMapper**, sans étape de build\n- **Three.js** pour le cerveau et l'univers en 3D\n- **GitHub Actions** pour les tests et le déploiement";
    private const CONTENU_EN = "## Software\n\n- **PhpStorm** for code\n- **Docker** to run everything locally as in production\n- **Claude Code** as a pair programmer\n\n## This site's stack\n\n- **PHP 8.5** and **Symfony 8**, **Doctrine** on **PostgreSQL**\n- **EasyAdmin** for the back office\n- **Stimulus** and **AssetMapper**, no build step\n- **Three.js** for the 3D brain and universe\n- **GitHub Actions** for tests and deployment";

    public function getDescription(): string
    {
        return 'Page /uses : table outils et premier contenu';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE outils (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu TEXT NOT NULL, maj_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, traductions JSON DEFAULT \'{}\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql(
            'INSERT INTO outils (contenu, maj_le, traductions) VALUES (:fr, NOW(), :traductions)',
            ['fr' => self::CONTENU_FR, 'traductions' => json_encode(['en' => ['contenu' => self::CONTENU_EN]])],
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE outils');
    }
}
