<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Livre d'or (#214) : messages des visiteurs, visibles une fois approuvés dans l'admin.
 */
final class Version20261009140026 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Livre d’or : table message_livre_or';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE message_livre_or (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cree_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, approuve BOOLEAN NOT NULL, prenom VARCHAR(40) NOT NULL, message VARCHAR(280) NOT NULL, langue VARCHAR(5) NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE message_livre_or');
    }
}
