<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Suivi des candidatures d'alternance (#228), dans l'admin seulement.
 */
final class Version20261009151426 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Candidatures : table candidature';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE candidature (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entreprise VARCHAR(100) NOT NULL, poste VARCHAR(150) NOT NULL, annonce VARCHAR(255) DEFAULT NULL, envoyee_le DATE NOT NULL, statut VARCHAR(20) NOT NULL, relancer_le DATE DEFAULT NULL, notes TEXT DEFAULT NULL, lien_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E33BD3B8EDAAC352 ON candidature (lien_id)');
        $this->addSql('ALTER TABLE candidature ADD CONSTRAINT FK_E33BD3B8EDAAC352 FOREIGN KEY (lien_id) REFERENCES lien_recruteur (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE candidature DROP CONSTRAINT FK_E33BD3B8EDAAC352');
        $this->addSql('DROP TABLE candidature');
    }
}
