<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Statistiques de visite maison (#230) : totaux par jour, page, langue et provenance, sans donnée personnelle.
 */
final class Version20261009153033 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Statistiques : table visite_jour';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE visite_jour (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, jour DATE NOT NULL, chemin VARCHAR(200) NOT NULL, langue VARCHAR(5) NOT NULL, source VARCHAR(100) NOT NULL, nombre INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_57667674DA17D9C5C42223289357758E5F8A7F73 ON visite_jour (jour, chemin, langue, source)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE visite_jour');
    }
}
