<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Blog (#192) : articles en Markdown, traduisibles, publiés à une date donnée (vide = brouillon).
 */
final class Version20261009100321 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Blog : table article';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE article (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(100) NOT NULL, titre VARCHAR(150) NOT NULL, resume VARCHAR(300) NOT NULL, contenu TEXT NOT NULL, image VARCHAR(255) DEFAULT NULL, publie_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, traductions JSON DEFAULT \'{}\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_23A0E66989D9B62 ON article (slug)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE article');
    }
}
