<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Créneaux d'entretien réservables par les recruteurs (/rendez-vous).
 */
final class Version20261010180000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Créneaux d’entretien';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE creneau (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, contact_nom VARCHAR(100) DEFAULT NULL, contact_email VARCHAR(180) DEFAULT NULL, lien_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F9668B5FE81B0679 ON creneau (debut)');
        $this->addSql('CREATE INDEX IDX_F9668B5FEDAAC352 ON creneau (lien_id)');
        $this->addSql('ALTER TABLE creneau ADD CONSTRAINT FK_F9668B5FEDAAC352 FOREIGN KEY (lien_id) REFERENCES lien_recruteur (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE creneau DROP CONSTRAINT FK_F9668B5FEDAAC352');
        $this->addSql('DROP TABLE creneau');
    }
}
