<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * DBAL 4 (Symfony 8) : les clés primaires passent de SERIAL (séquence + DEFAULT nextval)
 * à IDENTITY, et les commentaires « (DC2Type:…) » ne servent plus.
 * Le compteur de chaque table est recalé sur max(id) + 1 : sinon le prochain INSERT
 * repartirait à 1 et heurterait les lignes existantes.
 */
final class Version20261003170000 extends AbstractMigration
{
    private const TABLES = [
        'categorie_competence', 'centre_interet', 'competence', 'cv_competence', 'cv_profil',
        'demande_contact', 'etape_parcours', 'experience', 'journal', 'langue', 'passion',
        'projet', 'utilisateur',
    ];

    private const COMMENTAIRES = [
        'demande_contact.recu_le', 'journal.date', 'utilisateur.derniere_connexion',
    ];

    public function getDescription(): string
    {
        return 'Clés primaires en IDENTITY, commentaires DC2Type retirés (DBAL 4)';
    }

    public function up(Schema $schema): void
    {
        foreach (self::TABLES as $table) {
            $this->addSql("ALTER TABLE $table ALTER id DROP DEFAULT");
            $this->addSql("DROP SEQUENCE {$table}_id_seq"); // libère le nom pour la séquence de l'identité
            $this->addSql("ALTER TABLE $table ALTER id ADD GENERATED BY DEFAULT AS IDENTITY");
            $this->addSql("SELECT setval(pg_get_serial_sequence('$table', 'id'), COALESCE(MAX(id), 0) + 1, false) FROM $table");
        }
        foreach (self::COMMENTAIRES as $colonne) {
            $this->addSql("COMMENT ON COLUMN $colonne IS NULL");
        }
    }

    public function down(Schema $schema): void
    {
        foreach (self::TABLES as $table) {
            $this->addSql("ALTER TABLE $table ALTER id DROP IDENTITY");
            $this->addSql("CREATE SEQUENCE {$table}_id_seq OWNED BY $table.id");
            $this->addSql("SELECT setval('{$table}_id_seq', COALESCE(MAX(id), 0) + 1, false) FROM $table");
            $this->addSql("ALTER TABLE $table ALTER id SET DEFAULT nextval('{$table}_id_seq')");
        }
        foreach (self::COMMENTAIRES as $colonne) {
            $this->addSql("COMMENT ON COLUMN $colonne IS '(DC2Type:datetime_immutable)'");
        }
    }
}
