<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Mode recruteur (#213) : liens /?pour=code créés dans l'admin, avec leurs visites.
 */
final class Version20261009130922 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Liens recruteur : table lien_recruteur';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE lien_recruteur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(16) NOT NULL, entreprise VARCHAR(100) NOT NULL, poste VARCHAR(150) DEFAULT NULL, message TEXT DEFAULT NULL, visites INT NOT NULL, premiere_visite TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, derniere_visite TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C963BFB477153098 ON lien_recruteur (code)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE lien_recruteur');
    }
}
