<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Page /now (#203) : une seule ligne, modifiée dans l'administration. Premier contenu : à compléter.
 */
final class Version20261009110100 extends AbstractMigration
{
    private const CONTENU_FR = "## Je construis\n\nCe portfolio, en continu : dernièrement un blog et une palette de commandes (Ctrl+K).";
    private const CONTENU_EN = "## What I'm building\n\nThis portfolio, continuously: most recently a blog and a command palette (Ctrl+K).";

    public function getDescription(): string
    {
        return 'Page /now : table maintenant et premier contenu';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE maintenant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu TEXT NOT NULL, maj_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, traductions JSON DEFAULT \'{}\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql(
            'INSERT INTO maintenant (contenu, maj_le, traductions) VALUES (:fr, NOW(), :traductions)',
            ['fr' => self::CONTENU_FR, 'traductions' => json_encode(['en' => ['contenu' => self::CONTENU_EN]])],
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE maintenant');
    }
}
